server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, yupi
      routes:
        # 定义了一个名为"api_route"的路由规则,该规则将匹配以"/api/"开头的路径,例如"/api/user",
        # 并将这些请求转发到"http://localhost:8123"这个目标地址
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**



#      routes:
#        - id: add_request_header_route
#          uri: http://localhost:8123
#          predicates:
#            - Path=/api/**
#          filters:
#            - AddRequestHeader=hjc123123, swag
#            - AddRequestParameter=name, f3gggse
#      default-filters: # 全局过滤器
#        - AddRequestHeader=source, hjc
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
